### ISSUE TITLE
Upload to Python Package Index

### ISSUE THREAD

**Issue by hexatester** [userbotindo/Anjani#19]
Because the project name Anjani on pypi does not exist (yet), can we upload this project to pypi, 

- [ ] setup.py and / or setup.cfg (include language folder to setup configuration)
- [ ] Add [entry point(s)](https://packaging.python.org/specifications/entry-points/) (anjani_bot.\_\_main\_\_:main) to anjani-bot. (instead `python -m anjani_bot` we can just use `anjani-bot`)
- [ ] argparse for configuration via command only
- [ ] github action for upload to pypi

Example project that might help <https://github.com/python-telegram-bot/python-telegram-bot>

**Comment by keselekpermen69** [comment]
Hi. Currently we still have no intention for uploading this project to PyPI in the near future. we might do it on 2.0 (after all our draft published) or even later.
