### ISSUE TITLE
Remove `chat_action` plugin event

### ISSUE THREAD

**Issue by EverythingSuckz** [userbotindo/Anjani#196]
### Describe the feature you'd like to request

I've noticed that `chat_action` event handles user joins and left events but seems like `chat_member_update` already does the join and left events in a more efficient way since the `chat_member_update` event gives access to the [ChatMember](https://docs.pyrogram.org/api/types/ChatMember#pyrogram.types.ChatMember) class that holds information that the [Message](https://docs.pyrogram.org/api/types/Message) object lacks.

### Contributing

No, I am afraid I can't contribute this feature

**Comment by MrMissx** [comment]
Hi

[`on_chat_member_update()`](https://userbotindo.com/anjani/docs/plugin#on-chat-member-updated-listener) listener that handle joins and left member is a bug. That listener is only intended to use when a user is promoted or demoted and those joins and left event should be registered under [`on_chat_action()`](https://userbotindo.com/anjani/docs/plugin#on-chat-action-listener) as written on our docs.

https://github.com/userbotindo/Anjani/blob/a25bb7a1231614e8d16984b605780f7f3ce7b24c/anjani/core/telegram_bot.py#L262-L265

And yes it seems better to use the `ChatMemberUpdatedHandler` to register join/leave event. This will allow more operation with the `ChatMember` object. But as I read [`ChatMemberUpdated`](https://docs.pyrogram.org/api/types/ChatMemberUpdated#pyrogram.types.ChatMemberUpdated) there is no service message provided. We still need service message information for current delete service message on `welcome` plugin. We can still workaround with other listener that only listen to service message event.

wdyt @adekmaulana

**Comment by adekmaulana** [comment]
I thought about that before but as mentioned by @MrMissx there were some service of some codes that need data from `Message` object. So for now it's better to use the current for me, maybe later someone could find a better solution.

**Comment by EverythingSuckz** [comment]
> I thought about that before but as mentioned by @MrMissx there were some service of some codes that need data from `Message` object. So for now it's better to use the current for me, maybe later someone could find a better solution.

@adekmaulana Well I just found that [`on_chat_member_update()`](https://userbotindo.com/anjani/docs/plugin#on-chat-member-updated-listener) gets called for user promotions / demotions which is bad. I feel this issue is unnecessary now.

Initially, I wanted to get `invited_by` from the service message but the [`Message`](https://docs.pyrogram.org/api/types/Message) object don't have that. Thanks to @MrMissx, I found [`get_chat_member()`](https://docs.pyrogram.org/api/methods/get_chat_member#get-chat-member) will return [`ChatMember`](https://docs.pyrogram.org/api/types/ChatMember#pyrogram.types.ChatMember) which contains those info. Thank you for looking into this issue.
