### ISSUE TITLE
automatic backups

### ISSUE THREAD

**Issue by deltaxdump** [userbotindo/Anjani#273]
### Describe the feature you'd like to request

automatic periodic backups

### Describe the solution you'd like

automatic backups at regular intervals, such as 1 day, 2 days, and so on...

thanks before :)

**Comment by MrMissx** [comment]
Is it the plugin setting backup?
If yes, then I don't think this is necessary as those chat setting that the admin setup isn't changed periodically. Hence I don't think there is need to implement a periodic backup.

cc @adekmaulana

**Comment by adekmaulana** [comment]
> Is it the plugin setting backup? If yes, then I don't think this is necessary as those chat setting that the admin setup isn't changed periodically. Hence I don't think there is a need to implement a periodic backup.
> 
> cc @adekmaulana

i agree, most of the admins/owner of the chats doesn't even care about their backup
