### ISSUE TITLE
REQUEST

### ISSUE THREAD

**Issue by TheFunkyFox** [userbotindo/Anjani#306]
### Describe the feature you'd like to request

FEATURE REQUEST

### Describe the solution you'd like

Hello Sir, please Add Database Saved User's Broadcast Feautures on Anjani this repo...... Kindly Feauture request.

**Comment by MrMissx** [comment]
Broadcast are only available for the Bot owner and only broadcast to a group that the bot joins. We do not have any planning to implement user broadcast as it might be annoying for the users to get a broadcast from the bot directly. It is also against our values to overcome _SPAM_ on Telegram.
